default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: root
  password: password

development:
  <<: *default
  database: gardenscheduler_development

test:
  <<: *default
  database: gardenscheduler_test

production:
  <<: *default
  database: gardenscheduler_production
  username: root
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
